version: '3.8'

services:
  webapp-dev:
    build:
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - NEXT_TELEMETRY_DISABLED=1
    volumes:
      # Mount source code for hot reloading
      - .:/app
      # Exclude node_modules to avoid conflicts
      - /app/node_modules
      # Exclude .next build directory
      - /app/.next
    restart: unless-stopped

networks:
  default:
    name: webapp-dev-network 